### ISSUE TITLE
Supporting different name in extension

### ISSUE THREAD

**Issue by chmielsen** [dangmai/vscode-workspace-default-settings#189]
Currently the only name the settings are read from is `settings.default.json`. It'd be great to have it being pulled from extension settings. The use-case I'm thinking of: I want to have `settings.default.jsonc` file, given that the settings are allowing comments. That'd make comments not being highlighted as erroring in GitHub.

**Comment by dangmai** [comment]
Hello, sorry for the late response. I'm not sure why I didn't get the notification about your request.

I think it's a reasonable request, I'll put it on my list of TODO for this library. Thanks for opening the ticket!

**Comment by dangmai** [comment]
I have released a new version of this package that supports this feature.

You can now change the `workspace-default-settings.defaultSettingsFileName` setting to your desired file name.
