### ISSUE TITLE
Support JSON with trailing commas

### ISSUE THREAD

**Issue by Spitfire1900** [dangmai/vscode-workspace-default-settings#243]
VSCode supports JSON with trailing commas in settings.json; if this exists the program will exit with `[error] Error: Failed to parse settings.json. Please make sure it contains correct JSON content.`

This also occurs if you have a trailing comma in settings.default.json. Trailing commas also reduce diff lines as an extra configuration option will only add `+1` lines rather than `-1,+1` lines.

On the aside, settings.json will automatically use `jsonc` language mode in VSCode. Perhaps this extension should support reading from `.vscode/settings.default.jsonc`.

**Comment by dangmai** [comment]
Hi, thank you for the suggestion. I've published a new version that supports trailing commas in both setting files.

The extension also does support JSONC format (that's the parser I use), you can put comments directly in the `.vscode/settings.default.json` file, or you can create the `.vscode/settings.default.jsonc` file and set the `workspace-default-settings.defaultSettingsFileName` setting to be `settings.default.jsonc.
