### ISSUE TITLE
Look for settings.default.jsonc if settings.default.json does not exist prior to 

### ISSUE THREAD

**Issue by Spitfire1900** [dangmai/vscode-workspace-default-settings#310]
This extension supports jsonc but VSCode defaults to treating settings.default.json as a json document unless the following is persisted to settings.json.

```jsonc
{
    "files.associations": {
        "**/settings.default.json": "jsonc"
    },
}
```

Support falling back to looking for a settings.default.jsonc file as part of looking for the default settings file if settings.default.json does not exist.

**Comment by dangmai** [comment]
This extension has a setting for non-standard default file name already, it's called `workspace-default-settings.defaultSettingsFileName` (see [README](https://github.com/dangmai/vscode-workspace-default-settings#extension-settings)). You can set that to `settings.default.jsonc` in your global user settings if you regularly name it that way.

I do see the convenience factor if this is automatically baked into the extension, but I'm not planning on adding more complicated filename detection fallback.
