### ISSUE TITLE
Support VSCode settings.json intellisense in settings.default.json file

### ISSUE THREAD

**Issue by Spitfire1900** [dangmai/vscode-workspace-default-settings#311]
I'm not sure if there is a way to do this in the extension or with certain configuration settings in `settings.json` but I frequently am writing content for `settings.default.json` in `settings.json` instead because `settings.default.json` lacks the autocomplete capabilities that are available when editing the `settings.json` file. Then I copy and paste the new lines to settings.default.json.

It would be nice if `settings.default.json` could get the same intellisense as `settings.json` somehow.

**Comment by dangmai** [comment]
You can try putting this in your `settings.json` file:

```jsonc
{
  "json.schemas": [
    {
      "fileMatch": ["/.vscode/settings.default.json"],
      "url": "vscode://schemas/settings/folder"
    }
  ],
}
```
It works on my machine, let me know how it goes for you!
